id: P001668
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN6751
  title: དྲན་གསལ།
  author: ''
  volumes:
    8ddb60fcb6f748f19139595511885fb5:
      image_group_id: I3CN6753
      title: ''
      volume_number: 1
      total_pages: 102
      base_file: v001.txt
